# Generated by Django 3.1.2 on 2021-02-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(max_length=20)),
                ('ses', models.CharField(max_length=20)),
                ('sem', models.IntegerField()),
                ('sem_type', models.CharField(max_length=20)),
                ('prog', models.CharField(max_length=20)),
                ('bran', models.CharField(max_length=20)),
                ('spi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('p_cpi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cpi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('result', models.CharField(max_length=20)),
            ],
        ),
    ]
